name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [[ubuntu-latest, linux], [macos-latest, macos]]
        
    runs-on: ${{ matrix.os[0] }}

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: 'Upload artifact'
      uses: actions/upload-artifact@v4
      with:
        name: dpic-${{ matrix.os[1] }}
        path: dpic
